---
ansible_user: administrator
ansible_password: "{{ ansible_password }}"
ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_port: 5985
ansible_winrm_server_cert_validation: ignore
ansible_become: true
ansible_become_method: runas
ansible_become_user: administrator
ansible_become_password: "{{ ansible_password }}"